### ISSUE TITLE
Plugin nonfunctional in EPL 1.5.6

### ISSUE THREAD

**Issue by kremlinkev** [francois2metz/ep_github#3]
After enabling the plugin in EPL 1.5.6 (git shad31523aa08d123f421248e249e2194f7689f0b06) (nodejs v0.12.2 compiled from upstream source) and adding the documented settings to settings.json, the following stacktrace gets returned upon accessing the etherpad:

```
[2015-04-18 21:10:25.714] [ERROR] console - TypeError: Cannot set property 'github_redirect_url' of undefined
    at that.authenticate (/home/etherpad/etherpad-lite/node_modules/ep_github/node_modules/connect_auth_github/node_modules/connect-auth/lib/auth.strategies/github.js:74:48)
    at next (/home/etherpad/etherpad-lite/node_modules/ep_github/node_modules/connect_auth_github/node_modules/connect-auth/lib/strategyExecutor.js:60:37)
    at module.exports.authenticate (/home/etherpad/etherpad-lite/node_modules/ep_github/node_modules/connect_auth_github/node_modules/connect-auth/lib/strategyExecutor.js:66:11)
    at IncomingMessage.module.exports.authenticate (/home/etherpad/etherpad-lite/node_modules/ep_github/node_modules/connect_auth_github/node_modules/connect-auth/lib/requestMethods.js:72:23)
    at IncomingMessage.req.authenticate (/home/etherpad/etherpad-lite/node_modules/ep_github/node_modules/connect_auth_github/node_modules/connect-auth/lib/auth_middleware.js:76:37)
    at Object.handle (/home/etherpad/etherpad-lite/node_modules/ep_github/node_modules/connect_auth_github/node_modules/connect-auth/lib/auth.strategies/github.js:20:11)
    at next (/home/etherpad/etherpad-lite/node_modules/ep_github/node_modules/connect_auth_github/node_modules/connect-auth/node_modules/connect/lib/proto.js:190:15)
    at Object.auth [as handle] (/home/etherpad/etherpad-lite/node_modules/ep_github/node_modules/connect_auth_github/node_modules/connect-auth/lib/auth_middleware.js:99:7)
    at next (/home/etherpad/etherpad-lite/node_modules/ep_github/node_modules/connect_auth_github/node_modules/connect-auth/node_modules/connect/lib/proto.js:190:15)
    at Function.app.handle (/home/etherpad/etherpad-lite/node_modules/ep_github/node_modules/connect_auth_github/node_modules/connect-auth/node_modules/connect/lib/proto.js:198:3)
```

**Comment by JohnMcLear** [comment]
it looks like the upstream ``github-auth`` module got orphaned too: https://www.npmjs.com/package/connect_auth_github

I think https://www.npmjs.com/package/github-auth is a good alternative

**Comment by francois2metz** [comment]
Fixed thanks to @JohnMcLear. 

You should update to the 1.0.0 release with include some new features (filter by org, team or users).

**Comment by kremlinkev** [comment]
The updates look great, however I am still getting You shall not pass even after successfull auth with github. Has this been confirmed to work, or am is this user error?

Thanks!

**Comment by francois2metz** [comment]
What options are you using? Settings have changed since the previous release.

**Comment by kremlinkev** [comment]
Here is a sanitized excerpt from my settings.json

```json
"users": {
    "github": {
        "appId": "clientID hash",
        "appSecret": "client secret hash",
        "config": {
            "organization": "orgname",
            "users": ["kremlinkev"]
        }
    }
},
```

**Comment by francois2metz** [comment]
`users` and `organization` settings doesn't seems to work well together. You should try with only `organization` or `users`. 

FYI I tested the plugin in multiple conditions and it works well.

**Comment by kremlinkev** [comment]
I changed settings to just organization and just a single member user dict of myself, and I still get this. I can appreciate that it is a PEBKAC error at this point, and I appreciate the assistance! Just to confirm, in the github app config, what should my callback URL be?

**Comment by francois2metz** [comment]
In the github app, set the redirect uri to the root URI of your etherpad instance, `http://localhost:9001` for instance in an local install.

When you change your settings, do you clear any `code` parameter in the url of etherpad? After each change, go to http://localhost:9001 (or the url of your instance).

**Comment by kremlinkev** [comment]
I ended up giving up, deleting everything and just redeploying and creating a new github app. It appears to be working now. I assume I had some sort of cruft from previous versions, or moving through various checkouts of EPL in general. My ignorance of node probably is the larger issue here.

Thanks again for your help, and apologies for the time wasting red herring.

**Comment by francois2metz** [comment]
No problem. :kissing_cat:

**Comment by JohnMcLear** [comment]
Glad you got it working
